export const accData = [
  {
    id: 1,
    partName: "AIR SUCTION BRANCH",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "734.24",
    isChecked: false,
  },
  {
    id: 2,
    partName: "AUXILLARY BEARING",
    makerRef: "32104",
    drawingPos: "82000",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "99767",
    isChecked: false,
  },
  {
    id: 3,
    partName: "AXIAL BEARING",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "0",
    isChecked: false,
  },
  {
    id: 4,
    partName: "BEARING BUSH",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "98",
    isChecked: false,
  },
  {
    id: 5,
    partName: "BEARING CASINO",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "99767",
    isChecked: false,
  },
  {
    partName: "AUXILLARY BEARING",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "99767",
    isChecked: false,
  },
  {
    partName: "AUXILLARY BEARING",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "99767",
    isChecked: false,
  },
  {
    partName: "AUXILLARY BEARING",
    makerRef: "32104",
    drawingPos: "11.2",
    uom: "pcs",
    rob: "0",
    pendingOrders: "4",
    reqQty: "10",
    lastPurchase: "99767",
    isChecked: false,
  },
];
