trigger:
  batch: true
  branches:
    include:
      - main

# name: $(SourceBranchName).$(Date:yyyy-MM-dd)$(Rev:.r)
name: "purchaseOrder-frontend-latest"

resources:
  - repo: self

pool:
  vmImage: ubuntu-20.04

variables:
  tag: $(Build.BuildNumber)

steps:

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(serviceName)
    command: build
    Dockerfile: $(Build.SourcesDirectory)/Dockerfile
    tags: $(tag)

- task: Docker@2
  displayName: Push image to DockerHub
  inputs:
    containerRegistry: $(containerRegistry)
    repository: $(serviceName)
    command: push
    tags: $(tag)